version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Tokyo
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Tokyo
    groups: 
      patch-change:
        update-types: 
          - patch
      large-changes:
        update-types:
          - minor
          - major