version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Tokyo
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      timezone: Asia/Tokyo
    groups: 
      update-types: patch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: Asia/Tokyo
    groups:
      patterns:
        - "*"